import { GoogleGenAI, Modality, Type } from "@google/genai";
import type { 
  ImageData, 
  ImageValidationResponse, 
  VisualizationRequest, 
  VisualizationResponse 
} from '@repo/types';
import {
  getSystemPromptFromTemplate,
  getValidationPromptFromTemplate,
} from '@repo/prompt-templates';

/**
 * Get the system prompt from JSON template
 * The template can be edited at: packages/prompt-templates/templates/system-v1.json
 */
function getSystemPrompt(): string {
  return getSystemPromptFromTemplate().text;
}

/**
 * Get the validation prompt from JSON template
 * The template can be edited at: packages/prompt-templates/templates/validation-v1.json
 */
function getValidationPrompt(): string {
  const prompt = getValidationPromptFromTemplate().text;
  console.log('[VALIDATION PROMPT]:', prompt.substring(0, 200) + '...');
  return prompt;
}

export interface GeminiConfig {
  apiKey: string;
}

/**
 * Generate a photorealistic visualization of a shower glass installation
 */
export async function generateVisualization(
  config: GeminiConfig,
  request: VisualizationRequest
): Promise<VisualizationResponse> {
  const { apiKey } = config;
  const { bathroomImage, inspirationImage, prompt } = request;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is required');
  }

  if (!bathroomImage || !prompt) {
    throw new Error('bathroomImage and prompt are required');
  }

  const ai = new GoogleGenAI({ apiKey });

  // Build the parts array
  const parts: any[] = [];

  // Add bathroom image
  parts.push({
    inlineData: {
      data: bathroomImage.data,
      mimeType: bathroomImage.mimeType
    }
  });

  // Add inspiration image if provided
  if (inspirationImage) {
    parts.push({
      inlineData: {
        data: inspirationImage.data,
        mimeType: inspirationImage.mimeType
      }
    });
  }

  // Add text prompt
  parts.push({ text: prompt });

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts },
    config: {
      systemInstruction: getSystemPrompt(),
      responseModalities: [Modality.IMAGE],
    },
  });

  // Extract the generated image
  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64ImageBytes: string = part.inlineData.data;
      return {
        image: `data:image/png;base64,${base64ImageBytes}`
      };
    }
  }

  throw new Error("No image was generated by the model.");
}

/**
 * Validate an image and detect shower shape
 */
export async function validateImage(
  config: GeminiConfig,
  imageData: ImageData
): Promise<ImageValidationResponse> {
  const { apiKey } = config;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is required');
  }

  if (!imageData.data || !imageData.mimeType) {
    throw new Error('imageData and mimeType are required');
  }

  const ai = new GoogleGenAI({ apiKey });

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: {
      parts: [
        {
          inlineData: { 
            data: imageData.data, 
            mimeType: imageData.mimeType 
          }
        },
        {
          text: getValidationPrompt()
        }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          isValid: { type: Type.BOOLEAN },
          reason: { type: Type.STRING, description: "Short error message if invalid." },
          shape: { type: Type.STRING, enum: ["standard", "neo_angle", "tub"] }
        },
        required: ["isValid", "shape"]
      },
    },
  });

  const text = response.text;
  if (!text) {
    return {
      valid: false,
      reason: "Could not analyze image.",
      shape: "standard"
    };
  }

  const result = JSON.parse(text);
  return {
    valid: result.isValid,
    reason: result.reason,
    shape: result.shape || "standard"
  };
}
