import { GoogleGenAI, Modality, Type } from "@google/genai";
import type { 
  ImageData, 
  ImageValidationResponse, 
  VisualizationRequest, 
  VisualizationResponse 
} from '@repo/types';
import {
  getSystemPromptFromTemplate,
  getValidationPromptFromTemplate,
} from '@repo/prompt-templates';

/**
 * Get the system prompt from JSON template
 * The template can be edited at: packages/prompt-templates/templates/system-v1.json
 */
function getSystemPrompt(): string {
  return getSystemPromptFromTemplate().text;
}

/**
 * Get the validation prompt from JSON template
 * The template can be edited at: packages/prompt-templates/templates/validation-v1.json
 */
function getValidationPrompt(): string {
  const prompt = getValidationPromptFromTemplate().text;
  console.log('[VALIDATION PROMPT]:', prompt.substring(0, 200) + '...');
  return prompt;
}

export interface GeminiConfig {
  apiKey: string;
}

/**
 * Generate a photorealistic visualization of a shower glass installation
 */
export async function generateVisualization(
  config: GeminiConfig,
  request: VisualizationRequest
): Promise<VisualizationResponse> {
  const { apiKey } = config;
  const { bathroomImage, inspirationImage, prompt } = request;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is required');
  }

  if (!bathroomImage || !prompt) {
    throw new Error('bathroomImage and prompt are required');
  }

  const ai = new GoogleGenAI({ apiKey });

  // Build the parts array
  const parts: any[] = [];

  // Add bathroom image
  parts.push({
    inlineData: {
      data: bathroomImage.data,
      mimeType: bathroomImage.mimeType
    }
  });

  // Add inspiration image if provided
  if (inspirationImage) {
    parts.push({
      inlineData: {
        data: inspirationImage.data,
        mimeType: inspirationImage.mimeType
      }
    });
  }

  // Add text prompt
  parts.push({ text: prompt });

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts },
    config: {
      systemInstruction: getSystemPrompt(),
      responseModalities: [Modality.IMAGE],
      temperature: 0.3,
    },
  });

  // Extract the generated image
  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64ImageBytes: string = part.inlineData.data;
      return {
        image: `data:image/png;base64,${base64ImageBytes}`
      };
    }
  }

  throw new Error("No image was generated by the model.");
}

/**
 * Validate an image and detect shower shape
 */
export async function validateImage(
  config: GeminiConfig,
  imageData: ImageData
): Promise<ImageValidationResponse> {
  const { apiKey } = config;

  console.log('[GEMINI validateImage] Starting validation');

  if (!apiKey) {
    console.error('[GEMINI validateImage] API key missing');
    throw new Error('GEMINI_API_KEY is required');
  }

  if (!imageData.data || !imageData.mimeType) {
    console.error('[GEMINI validateImage] Invalid image data', {
      hasData: !!imageData.data,
      mimeType: imageData.mimeType
    });
    throw new Error('imageData and mimeType are required');
  }

  console.log('[GEMINI validateImage] Image data valid, length:', imageData.data.length);

  try {
    const ai = new GoogleGenAI({ apiKey });
    console.log('[GEMINI validateImage] GoogleGenAI client created');

    const validationPrompt = getValidationPrompt();
    console.log('[GEMINI validateImage] Using validation prompt:', validationPrompt.substring(0, 100) + '...');

    console.log('[GEMINI validateImage] Calling Gemini API...');
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
          {
            inlineData: { 
              data: imageData.data, 
              mimeType: imageData.mimeType 
            }
          },
          {
            text: validationPrompt
          }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            isValid: { type: Type.BOOLEAN },
            reason: { type: Type.STRING, description: "Short user-friendly error message if invalid." },
            contentFlag: { type: Type.STRING, enum: ["safe", "pii", "inappropriate"] },
            shape: { type: Type.STRING, enum: ["standard", "neo_angle", "tub"] },
            detectedHardware: { type: Type.STRING, enum: ["chrome", "brushed_nickel", "matte_black", "polished_brass", "oil_rubbed_bronze", "none"] }
          },
          required: ["isValid", "contentFlag", "shape", "detectedHardware"]
        },
      },
    });

    console.log('[GEMINI validateImage] API response received');
    const text = response.text;
    console.log('[GEMINI validateImage] Response text:', text);

    if (!text) {
      console.error('[GEMINI validateImage] Empty response text');
      return {
        valid: false,
        reason: "Could not analyze image.",
        shape: "standard",
        detectedHardware: "none"
      };
    }

    const result = JSON.parse(text);
    console.log('[GEMINI validateImage] Parsed result:', result);

    const contentFlag = result.contentFlag || 'safe';

    // Override reason with user-friendly messages for content safety issues
    let reason = result.reason;
    if (contentFlag === 'pii') {
      reason = 'This image appears to contain personal information (such as a visible face or personal documents). Please upload a photo of just the bathroom/shower area without people or personal items visible.';
    } else if (contentFlag === 'inappropriate') {
      reason = 'This image contains content that cannot be processed. Please upload an appropriate photo of your bathroom or shower area.';
    }

    return {
      valid: result.isValid,
      reason,
      shape: result.shape || "standard",
      detectedHardware: result.detectedHardware || "none",
      contentFlag,
    };
  } catch (error) {
    console.error('[GEMINI validateImage] Error during validation:', error);
    throw error;
  }
}
