import React from 'react';

export const TermsOfUse: React.FC = () => (
  <>
    <p><strong>Effective Date:</strong> March 26, 2026</p>
    <p><strong>Last Updated:</strong> March 26, 2026</p>

    <p>
      These Terms of Use (&ldquo;Terms&rdquo;) govern your access to and use of the GatsbyView
      AI-powered shower visualization tool (the &ldquo;Service&rdquo;) operated by Horse Power
      Brands, LLC and its affiliated Gatsby Glass franchise entities (&ldquo;Gatsby Glass,&rdquo;
      &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By accessing or using the
      Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
    </p>

    <h3>1. Service Description</h3>
    <p>
      The Service is an AI-powered visualization tool that allows users to upload photographs of
      their bathroom or shower area and receive computer-generated renderings showing how various
      glass enclosure configurations, hardware finishes, and door styles might appear in their
      space. The Service utilizes artificial intelligence technology to generate these
      visualizations and is intended for informational and consultation purposes only.
    </p>

    <h3>2. Eligibility</h3>
    <p>
      You must be at least 18 years of age, or the age of majority in your jurisdiction, to use the
      Service. If you are under 18, you may only use the Service with the involvement and consent of
      a parent or legal guardian. The Service is designed for use within the United States.
    </p>

    <h3>3. User Accounts</h3>
    <p>
      The Service may be used without creating an account. Certain features, such as franchise team
      access, require authentication via an email-based magic link. Team access is limited to
      authorized email addresses registered in our franchise directory. You are responsible for
      maintaining the confidentiality of your login credentials and for all activity that occurs
      under your account. Unauthorized access attempts or sharing of team credentials is prohibited.
    </p>

    <h3>4. Acceptable Use</h3>
    <p>When using the Service, you agree that you will not:</p>
    <ul>
      <li>
        Upload images containing identifiable people, faces, or individuals. The Service includes
        automated validation that may reject such images.
      </li>
      <li>
        Upload images containing offensive, obscene, illegal, or otherwise inappropriate content.
      </li>
      <li>
        Upload images that you do not have the right to use, or that infringe on any third
        party&rsquo;s intellectual property, privacy, or other rights.
      </li>
      <li>
        Attempt to circumvent, disable, or interfere with the Service&rsquo;s rate-limiting
        mechanisms, security features, or access controls.
      </li>
      <li>
        Use automated tools, bots, scrapers, or other programmatic means to access, collect data
        from, or interact with the Service.
      </li>
      <li>
        Reverse engineer, decompile, or attempt to extract the source code, AI models, or
        proprietary algorithms used by the Service.
      </li>
      <li>
        Use the Service for any unlawful purpose or in violation of any applicable local, state,
        national, or international law.
      </li>
      <li>
        Interfere with or disrupt the integrity or performance of the Service or the data contained
        therein.
      </li>
      <li>
        Impersonate any person or entity or misrepresent your affiliation with any person or entity.
      </li>
    </ul>

    <h3>5. AI-Generated Content Disclaimer</h3>
    <p>
      <strong>
        Visualizations generated by the Service are AI-produced approximations and are not
        guarantees of final product appearance.
      </strong>{' '}
      You acknowledge and agree that:
    </p>
    <ul>
      <li>
        Colors, textures, dimensions, proportions, and materials shown in visualizations may differ
        significantly from actual installed products.
      </li>
      <li>
        AI-generated images may contain visual artifacts, inaccuracies, or distortions that do not
        reflect real-world conditions.
      </li>
      <li>
        Visualizations should not be relied upon as engineering specifications, construction
        documents, or precise measurements.
      </li>
      <li>
        The actual appearance of installed glass, hardware, and fixtures will depend on lighting
        conditions, manufacturing variations, installation methods, and other real-world factors
        beyond the scope of this tool.
      </li>
      <li>
        Gatsby Glass and its franchise partners are not bound by the visual representations produced
        by this Service when quoting, manufacturing, or installing products.
      </li>
    </ul>

    <h3>6. Intellectual Property</h3>

    <h4>Your Content</h4>
    <p>
      You retain all ownership rights to the photographs you upload. By uploading images, you grant
      us a limited, non-exclusive license to process, transmit, and temporarily store those images
      as necessary to provide the Service. You represent and warrant that you have all rights
      necessary to upload and share any images you provide.
    </p>

    <h4>Generated Visualizations</h4>
    <p>
      AI-generated visualizations are provided for your personal use and for consultation with
      Gatsby Glass franchise professionals. You may share your visualizations for personal,
      non-commercial purposes. You may not use generated visualizations for commercial purposes,
      advertising, or resale without our prior written consent. Watermarked images may not be
      altered, modified, or processed to remove or obscure the watermark.
    </p>

    <h4>Our Intellectual Property</h4>
    <p>
      The Service, including its design, user interface, branding, logos, software, AI models,
      prompt templates, and all related intellectual property, is owned by Horse Power Brands, LLC
      and/or its licensors. The Gatsby Glass name, GatsbyView name, and associated logos and
      trademarks are the property of Horse Power Brands, LLC. Nothing in these Terms grants you any
      right to use our trademarks, trade names, or branding.
    </p>

    <h3>7. Franchise Relationship Disclaimer</h3>
    <p>
      Gatsby Glass operates through a network of independently owned and operated franchise
      locations. Horse Power Brands, LLC is the franchisor. Each franchise is an independent
      business, and the franchisor is not responsible for the acts, omissions, pricing, scheduling,
      or service quality of any individual franchise location. Experiences, availability, and
      pricing may vary by location. When you submit a lead form or request a quote, you will be
      connected with the franchise location serving your area, which operates as an independent
      entity.
    </p>

    <h3>8. Usage Limits</h3>
    <p>
      Non-authenticated users are subject to a monthly limit on the number of AI visualizations
      that may be generated. These limits are enforced per browser session and IP address. We
      reserve the right to modify usage limits at any time. Authenticated franchise team members
      may be exempt from certain usage restrictions.
    </p>

    <h3>9. Data and Privacy</h3>
    <p>
      Your use of the Service is also governed by our Privacy Policy, which describes how we
      collect, use, and protect your information. By using the Service, you consent to the data
      practices described in the Privacy Policy. Generated visualization images are accessible via
      direct URLs and are not protected by additional access controls. Do not include sensitive or
      confidential information in uploaded images.
    </p>

    <h3>10. Disclaimer of Warranties</h3>
    <p>
      <strong>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT
        WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
      </strong>{' '}
      To the fullest extent permitted by applicable law, we disclaim all warranties, including but
      not limited to implied warranties of merchantability, fitness for a particular purpose, title,
      and non-infringement. We do not warrant that:
    </p>
    <ul>
      <li>The Service will be uninterrupted, timely, secure, or error-free.</li>
      <li>
        The results or visualizations generated by the Service will be accurate, reliable, or meet
        your expectations.
      </li>
      <li>
        Any defects in the Service will be corrected.
      </li>
      <li>
        The Service is free of viruses or other harmful components.
      </li>
    </ul>

    <h3>11. Limitation of Liability</h3>
    <p>
      <strong>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL GATSBY GLASS, HORSE
        POWER BRANDS, LLC, THEIR AFFILIATES, FRANCHISE PARTNERS, OFFICERS, DIRECTORS, EMPLOYEES,
        AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
        PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES,
        RESULTING FROM:
      </strong>
    </p>
    <ul>
      <li>Your access to, use of, or inability to use the Service.</li>
      <li>
        Any conduct or content of any third party on or related to the Service, including any
        defamatory, offensive, or illegal conduct.
      </li>
      <li>
        Any content or visualizations obtained from or generated by the Service.
      </li>
      <li>
        Unauthorized access, use, or alteration of your transmissions, content, or data.
      </li>
      <li>
        Decisions made based on AI-generated visualizations, including purchasing, remodeling, or
        construction decisions.
      </li>
    </ul>
    <p>
      Our total aggregate liability to you for all claims arising out of or relating to these Terms
      or the Service shall not exceed one hundred US dollars ($100.00).
    </p>

    <h3>12. Indemnification</h3>
    <p>
      You agree to indemnify, defend, and hold harmless Gatsby Glass, Horse Power Brands, LLC,
      their franchise partners, affiliates, officers, directors, employees, and agents from and
      against any claims, liabilities, damages, losses, costs, and expenses (including reasonable
      attorneys&rsquo; fees) arising out of or in any way related to: (a) your use of or access to
      the Service; (b) your violation of these Terms; (c) your violation of any third party right,
      including any intellectual property or privacy right; or (d) any content you upload to or
      transmit through the Service.
    </p>

    <h3>13. Governing Law and Dispute Resolution</h3>
    <p>
      These Terms shall be governed by and construed in accordance with the laws of the State of
      Oklahoma, without regard to its conflict of law provisions. Any dispute arising out of or
      relating to these Terms or the Service shall be resolved exclusively in the state or federal
      courts located in Oklahoma County, Oklahoma, and you consent to the personal jurisdiction of
      such courts. You agree to waive any right to a jury trial in connection with any action or
      litigation arising under or relating to these Terms.
    </p>

    <h3>14. Modifications to Terms</h3>
    <p>
      We reserve the right to modify these Terms at any time. When we make material changes, we
      will update the &ldquo;Last Updated&rdquo; date at the top of these Terms. Your continued use
      of the Service following any changes constitutes your acceptance of the revised Terms. If you
      do not agree to the updated Terms, you must discontinue your use of the Service.
    </p>

    <h3>15. Termination</h3>
    <p>
      We reserve the right to suspend or terminate your access to the Service at any time, with or
      without cause and with or without notice. Upon termination, all provisions of these Terms
      that by their nature should survive termination shall survive, including but not limited to
      ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
    </p>

    <h3>16. Severability</h3>
    <p>
      If any provision of these Terms is held to be invalid, illegal, or unenforceable, the
      remaining provisions shall continue in full force and effect. The invalid or unenforceable
      provision shall be modified to the minimum extent necessary to make it valid and enforceable.
    </p>

    <h3>17. Entire Agreement</h3>
    <p>
      These Terms, together with the Privacy Policy, constitute the entire agreement between you
      and Gatsby Glass regarding the Service and supersede all prior or contemporaneous
      understandings and agreements, whether written or oral, regarding the Service.
    </p>

    <h3>18. Contact Us</h3>
    <p>
      If you have questions or concerns about these Terms, please contact us at:
    </p>
    <p>
      <strong>Horse Power Brands, LLC</strong><br />
      Attn: Legal<br />
      Email:{' '}
      <a href="mailto:legal@horsepowerbrands.com">legal@horsepowerbrands.com</a><br />
      Website:{' '}
      <a
        href="https://www.horsepowerbrands.com"
        target="_blank"
        rel="noopener noreferrer"
      >
        www.horsepowerbrands.com
      </a>
    </p>
  </>
);
